
#make: 
#	gcc  database.h sorted_link_list_1.c print_database3.c main.c delete4.c insert_row2.c -o db


#make file - this is a comment section
 
CC=gcc  #compiler
TARGET=dataBase #target file name
 
all:  database.h sorted_link_list_1.o print_database3.o main.o delete4.o insert_row2.o .
  $(CC) database.h sorted_link_list_1.c print_database3.c main.c delete4.c insert_row2.c  -o $(TARGET)
 
clean:
  rm *.o $(TARGET)
